Use a custom LDAP filter during a DCSync in secretsdump.py
fortra/impacket pull request #1329
Opened 2022-05-29 09:53 UTC by snovvcrash

Reopening this PR from #1090 due to merging conflicts.

![1](https://user-images.githubusercontent.com/23141800/170862186-a7008599-8330-405b-9a43-9218c3be610c.png)

![2](https://user-images.githubusercontent.com/23141800/170862189-a66b97d9-6924-40bd-b98f-b0949f808a93.png)

@ShutdownRepo could you check if DCSync still happens twice for you, please?

2022-07-25 16:00 UTC, 0xdeaddood requested changes
Hi @snovvcrash!

Thanks for the PR, the addition is great. I have a couple of change requests before merging. Please check it out and let me know what do you think.

2022-07-25 17:11 UTC, snovvcrash commented on impacket/examples/secretsdump.py
> +    def getDomainUsersLDAP(self, searchFilter):
Added the check within the commit below.

2022-07-25 17:15 UTC, snovvcrash commented
Hey @0xdeaddood, thanks for the review!

Agree with your comments, I've resolved the changes 👍🏻

2022-07-25 23:25 UTC, 0xdeaddood approved these changes

2023-01-17 03:55 UTC, 0xdeaddood commented
Merging 🎉🎈 Thanks @snovvcrash!

2023-01-17 03:55 UTC, merged