Added query information level 0x0109 for smb1 "SMB_QUERY_FILE_STREAM_INFO"
fortra/impacket pull request #1550
Opened 2023-05-08 23:46 UTC by Adamkadaban

As per: https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-CIFS/%5BMS-CIFS%5D-180912.pdf

Fixes https://github.com/fortra/impacket/issues/105

2023-07-20 06:20 UTC, alexisbalbachan requested changes
Remove the .swp from the request, everything else is ok

2023-07-20 06:20 UTC, alexisbalbachan commented on impacket/.smb.py.swp
Please remove this file from the pull request

2023-07-20 12:59 UTC, Adamkadaban commented on impacket/.smb.py.swp
Sorry about that, not sure how I missed that. Everything should be good to go now

2023-08-17 06:18 UTC, alexisbalbachan approved these changes

2023-08-17 06:24 UTC, merged