[samedit.py] Added example script to edit local SAM hashes
fortra/impacket pull request #1761
Opened 2024-06-09 18:13 UTC by Iorpim

I recently encountered a scenario in which I needed to replace the hash of a local user in another machine and all usual solutions were either incomplete or outdated. After noticing `secretsdump.py` had all the necessary logic to parse user account structs inside the SAM hive it seemed like a simple change to allow it to modify the user data as well.

The `winregistry` package has been slightly modified to allow the writing of registry keys as well. Currently, the writing capabilities are quite limited and can only rewrite key values with the same length, which is enough for the working of the new script but could be expanded to provide a more generalized feature.

2024-06-11 13:06 UTC, Iorpim commented
Just did some minor cleanup of previous leftover commits

2025-07-24 04:01 UTC, alexisbalbachan commented on examples/samedit.py
> +    parser.add_argument('-hashes', action='store', help='Replace NTLM hash directly (LM hash is optional)')
Argument name does not match with future usages (defined as "**hashes**", but afterwards it is referenced as options.**hash**). Either change the name from hashes to hash or change every mention of options.hash to options.hashes (L86, L90, L102, L103, L105, L107)

2025-07-24 04:08 UTC, alexisbalbachan requested changes
Could you please rename (or reference correctly) the "hashes" variable? The PR also needs to be rebased to the latest version of Impacket. After those changes the example looks good and ready to merge!

2025-08-20 20:39 UTC, alexisbalbachan approved these changes
Rebased and applied requested changes

2025-08-20 20:46 UTC, merged

2026-03-01 00:03 UTC, Iorpim commented
> Could you please rename (or reference correctly) the "hashes" variable? The PR also needs to be rebased to the latest version of Impacket. After those changes the example looks good and ready to merge!

Oh, sorry, I somehow missed this; thank you for fixing it!