winregistry.py: handle value name containting backslash character
fortra/impacket pull request #1767
Opened 2024-06-25 17:22 UTC by DidierA

`winregistry.Registry.getValue()` splits keyValue on backslash to separate key and value. But  value names can contain backslash, and calling getValue on such a value will cause a ValueError exception.

This commit corrects this bug while keeping compatibility with old code.

2024-07-30 21:07 UTC, gabrielg5 requested changes
Hey @DidierA, thanks for your changes!

I've been reviewing them and posted some suggestions. Think they are cleaner this way according to our current use cases.

2024-07-30 21:07 UTC, gabrielg5 commented on examples/registry-read.py
> +        data = reg.getValue(key,value.decode('utf-8'))
```suggestion
        data = reg.getValue(searchKey, value.decode('utf-8'))
```

2024-07-30 21:07 UTC, gabrielg5 commented on impacket/winregistry.py
> +        """
just updating the function comment to reflect actual parameters...

```suggestion
        """ returns a tuple with (ValueType, ValueData) for the requested keyValue
            valueName is the name of the value (which can contain '\\')
            if valueName is not  given, keyValue must be a string containing the full path to the value
            if valueName is given, keyValue should be the string containing the path to the key containing valueName
        """
```

2024-07-30 21:07 UTC, gabrielg5 commented on impacket/winregistry.py
> +        key = None
```suggestion

```

2024-07-30 21:07 UTC, gabrielg5 commented on impacket/winregistry.py
> +            regValue = valueName
Think it's simpler this way. Only accepting a string as `keyValue`. Less code

```suggestion
            regKey = keyValue
            regValue = valueName
```

2024-07-30 21:07 UTC, gabrielg5 commented on impacket/winregistry.py
> +            key = self.findKey(regKey)
```suggestion
        key = self.findKey(regKey)
```

2024-08-15 19:24 UTC, gabrielg5 approved these changes

2024-08-15 19:25 UTC, gabrielg5 commented
Applied suggestions to move forward with the bug resolution

2024-08-19 19:56 UTC, anadrianmanrique approved these changes

2024-08-19 19:57 UTC, merged

2024-08-20 13:05 UTC, DidierA commented
Hi, Sorry for the late reply, I was on leave. The idea behind accepting a REG_NK was to allow multiple calls on the same key to reuse the result of findKey(), such as when you dump an entire tree.  However I don't have a problem with the reviewed changes.