Fix file length not matching file name because of multi-byte UTF-16
fortra/impacket pull request #1859
Opened 2024-12-05 09:00 UTC by rtpt-romankarwacik

Fixes https://github.com/fortra/impacket/issues/1796

Before, filenames with multi-byte symbols such as emojis cut off the filename in several cases:
![Screenshot from 2024-12-05 09-41-30](https://github.com/user-attachments/assets/27bf92cf-38ff-4ba6-9bf8-89679aa70c14)

There are still some of these left in the code, but I did not know if the encoding can be assumed in those cases, whereas in the cases I fixed it was already assumed to be UTF-16LE

Here is a rough grep for the remaining cases:

```bash
$ grep -REn "len\([^)]*\)\*2"
impacket/dcerpc/v5/samr.py:2838:        samUser['Buffer'] = b'A'*(512-len(newPassword)*2) + newPassword.encode('utf-16le')
impacket/dcerpc/v5/samr.py:2841:        samUser['Buffer'] = b'A'*(512-len(newPassword)*2) + newPassword.decode(sys.getfilesystemencoding()).encode('utf-16le')
impacket/dcerpc/v5/samr.py:2843:    samUser['Length'] = len(newPassword)*2
impacket/dcerpc/v5/dcom/oaut.py:276:            self['cBytes'] = len(value)*2
impacket/dcerpc/v5/dtypes.py:384:            self['Length'] = len(value)*2
impacket/dcerpc/v5/dtypes.py:385:            self['MaximumLength'] = len(value)*2
impacket/examples/ntlmrelayx/utils/shadow_credentials.py:108:    return "B:%d:%s:%s" % (len(binaryData)*2,hexdata,owner)
impacket/smb.py:927:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:956:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:987:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:1015:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:1030:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:1053:        ('FileNameLength','<L-FileName','len(FileName)*2'),
impacket/smb.py:1077:        ('FileNameLength','<B-FileName','len(FileName)*2'),
examples/karmaSMB.py:389:        ntCreateRequest['NameLength'] = len(targetFile)*2
tests/dcerpc/test_samr.py:326:        #entry.fields['MaximumLength'] = len('Administrator\x00')*2
tests/dcerpc/test_samr.py:2288:        samUser['Buffer'] = b'A'*(512-len(newPwd)*2) + newPwd.encode('utf-16le')
tests/dcerpc/test_samr.py:2289:        samUser['Length'] = len(newPwd)*2
tests/dcerpc/test_scmr.py:127:           self.assertEqual(arrayData[offset:][:len(changeDone)*2].decode('utf-16le'), changeDone)
tests/dcerpc/test_rrp.py:216:        request['cbData'] = len(self.test_value_data)*2
tests/misc/test_structure.py:81:            ('code1', '>L=len(arr1)*2+0x1000'),
tests/misc/test_structure.py:191:            ('leni', '<L=len(uno)*2'),
```

2025-01-16 02:37 UTC, alexisbalbachan requested changes
Hi, everything looks great, i've requested some minor corrections to avoid repeating code

2025-01-16 02:37 UTC, alexisbalbachan commented on impacket/smb3.py
> +        treeConnect['PathLength'] = len(path.encode('utf-16le'))
```suggestion
        treeConnect['PathLength'] = len(treeConnect['Buffer'])
```

2025-01-16 02:37 UTC, alexisbalbachan commented on impacket/smb3.py
>          queryDirectory['Buffer']             = searchString.encode('utf-16le')
```suggestion
        queryDirectory['Buffer']             = searchString.encode('utf-16le')
        queryDirectory['FileNameLength']     = len(queryDirectory['Buffer'])
        
```

2025-01-16 02:37 UTC, alexisbalbachan commented on impacket/smb3.py
>              renameReq['FileName']        = newPath.encode('utf-16le')
```suggestion
            renameReq['FileName']        = newPath.encode('utf-16le')
            renameReq['FileNameLength']  = len(renameReq['FileName'])

```

2025-01-16 02:37 UTC, alexisbalbachan commented on impacket/smb3.py
>          pipeWait['Name']             = pipename.encode('utf-16le')
```suggestion
        pipeWait['Name']             = pipename.encode('utf-16le')
        pipeWait['NameLength']       = len(pipeWait['Name'] )
        pipeWait['TimeoutSpecified'] = 1

```

2025-01-17 08:42 UTC, rtpt-romankarwacik commented
Suggestions look good :+1:

2025-01-23 02:11 UTC, alexisbalbachan approved these changes

2025-01-23 02:12 UTC, merged